### ISSUE TITLE
Bill Status processing is currently down

### ISSUE THREAD

**Issue by jonquandt** [usgpo/bill-status#185]
Some upstream changes are preventing us from updating BILLSTATUS XML files. We are investigating the issue and working with our data partners on a resolution.

**Comment by llaplant** [comment]
We are continuing to work with our data partners and hope to have service restored on Friday.

**Comment by camsmith** [comment]
The BILLSTATUS page appears to have updates now https://www.govinfo.gov/bulkdata/BILLSTATUS/117

Can you confirm that this issue has been resolved @jonquandt ? Thank you!

**Comment by jonquandt** [comment]
@camsmith - partially fixed. We're seeing a couple of field inconsistencies at this time, so we are processing new BILLSTATUS files now, but holding off on allowing updates to existing files until we can resolve them with our data partners. 

We appreciate your patience.

**Comment by jonquandt** [comment]
Update: The issues we were seeing have been resolved. We are about to turn on our update process to include updates from last week. This will take several hours, but you should see these updated files flowing through today. 

Keeping this open until that job is complete so we can ensure there are no issues downstream.

**Comment by jonquandt** [comment]
Closing this, as things have been proceeding as expected.
